#############################################################################
# Makefile for building: pdv
# Generated by qmake (2.01a) (Qt 4.5.2) on: Sat Jun 4 14:46:04 2011
# Project:  pdv.pro
# Template: app
# Command: /ifs/storage/ifs/otkach/Qt-4.5.2/bin/qmake -unix -o Makefile pdv.pro
#############################################################################

####### Compiler, tools and options

CC            = mpicc -cc=icc
CXX           = mpicxx -cxx=icpc
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -wd654,1572 -O2 -D_REENTRANT $(DEFINES)
CXXFLAGS      = -wd654,1572 -xSSE4.2 -Wall -w2 -Werror -wd2557 -wd981 -wd383 -wd869 -wd2407 -wd177 -wd2415 -O2 -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/linux-icc -I. -I../../../../storage/ifs/otkach/Qt-4.5.2/include/QtCore -I../../../../storage/ifs/otkach/Qt-4.5.2/include -I. -I.
LINK          = mpicxx -cxx=icpc
LFLAGS        = -Wl,-Map,pdv.map -Qoption,ld,-rpath,/ifs/storage/ifs/otkach/Qt-4.5.2/lib
LIBS          = $(SUBLIBS)  -L/ifs/storage/ifs/otkach/Qt-4.5.2/lib -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -liomp5 -lQtCore -L/ifs/storage/ifs/otkach/Qt-4.5.2/lib -lz -lm -pthread -L/lib64 -lgthread-2.0 -lglib-2.0 -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /ifs/storage/ifs/otkach/Qt-4.5.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = mpidistributions1.cpp \
		mpimainwindow.cpp \
		percol2d.cpp \
		PercolRectSides.cpp 
OBJECTS       = mpidistributions1.o \
		mpimainwindow.o \
		percol2d.o \
		PercolRectSides.o
DIST          = ../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/common/unix.conf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/qconfig.pri \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_functions.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_config.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/exclusive_builds.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_pre.prf \
		pdv.pri \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/release.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_post.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/warn_on.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/unix/thread.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/moc.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/resources.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/uic.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/yacc.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/lex.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/include_source_dir.prf \
		pdv.pro
QMAKE_TARGET  = pdv
DESTDIR       = 
TARGET        = pdv

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pdv.pro  ../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/linux-icc/qmake.conf ../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/common/unix.conf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/qconfig.pri \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_functions.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_config.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/exclusive_builds.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_pre.prf \
		pdv.pri \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/release.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_post.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/warn_on.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/unix/thread.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/moc.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/resources.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/uic.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/yacc.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/lex.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/include_source_dir.prf \
		/ifs/storage/ifs/otkach/Qt-4.5.2/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile pdv.pro
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/common/unix.conf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/qconfig.pri:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_functions.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_config.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/exclusive_builds.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_pre.prf:
pdv.pri:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/release.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_post.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/warn_on.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/unix/thread.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/moc.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/resources.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/uic.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/yacc.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/lex.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/include_source_dir.prf:
/ifs/storage/ifs/otkach/Qt-4.5.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile pdv.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pdv1.0.0 || $(MKDIR) .tmp/pdv1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pdv1.0.0/ && $(COPY_FILE) --parents mainwindow.h percol2d.h PercolRectSides.h .tmp/pdv1.0.0/ && $(COPY_FILE) --parents mpidistributions1.cpp mpimainwindow.cpp percol2d.cpp PercolRectSides.cpp .tmp/pdv1.0.0/ && (cd `dirname .tmp/pdv1.0.0` && $(TAR) pdv1.0.0.tar pdv1.0.0 && $(COMPRESS) pdv1.0.0.tar) && $(MOVE) `dirname .tmp/pdv1.0.0`/pdv1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pdv1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) -r $(OBJECTS_DIR)/ti_files
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

mpidistributions1.o: mpidistributions1.cpp percol2d.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpidistributions1.o mpidistributions1.cpp

mpimainwindow.o: mpimainwindow.cpp mainwindow.h \
		percol2d.h \
		PercolRectSides.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpimainwindow.o mpimainwindow.cpp

percol2d.o: percol2d.cpp percol2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o percol2d.o percol2d.cpp

PercolRectSides.o: PercolRectSides.cpp PercolRectSides.h \
		percol2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PercolRectSides.o PercolRectSides.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

