#############################################################################
# Makefile for building: percol2
# Generated by qmake (2.01a) (Qt 4.5.2) on: Fri Apr 29 23:22:35 2011
# Project:  percol2.pro
# Template: app
# Command: /ifs/storage/ifs/otkach/Qt-4.5.2/bin/qmake -unix -o Makefile percol2.pro
#############################################################################

####### Compiler, tools and options

CC            = icc
CXX           = icpc
DEFINES       = -DQT_QT3SUPPORT_LIB -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -wd654,1572 -g -D_REENTRANT $(DEFINES)
CXXFLAGS      = -wd654,1572 -g -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/linux-icc -I. -I../../../../storage/ifs/otkach/Qt-4.5.2/include/QtCore -I../../../../storage/ifs/otkach/Qt-4.5.2/include/QtGui -I/ifs/storage/ifs/otkach/Qt-4.5.2/include/Qt3Support -I../../../../storage/ifs/otkach/Qt-4.5.2/include -I. -I.
LINK          = icpc
LFLAGS        = -Qoption,ld,-rpath,/ifs/storage/ifs/otkach/Qt-4.5.2/lib
LIBS          = $(SUBLIBS)  -L/ifs/storage/ifs/otkach/Qt-4.5.2/lib -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lQt3Support -lQtGui -L/ifs/storage/ifs/otkach/Qt-4.5.2/lib -L/usr/X11R6/lib -pthread -L/lib64 -lpng -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lglib-2.0 -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /ifs/storage/ifs/otkach/Qt-4.5.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		myparam.cpp \
		percol2d.cpp \
		plotter.cpp moc_mainwindow.cpp \
		moc_myparam.cpp \
		moc_plotter.cpp
OBJECTS       = main.o \
		mainwindow.o \
		myparam.o \
		percol2d.o \
		plotter.o \
		moc_mainwindow.o \
		moc_myparam.o \
		moc_plotter.o
DIST          = ../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/common/unix.conf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/qconfig.pri \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_functions.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_config.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/exclusive_builds.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_pre.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/debug.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_post.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/warn_on.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/unix/thread.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/moc.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/resources.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/uic.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/yacc.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/lex.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/include_source_dir.prf \
		percol2.pro
QMAKE_TARGET  = percol2
DESTDIR       = 
TARGET        = percol2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: percol2.pro  ../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/linux-icc/qmake.conf ../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/common/unix.conf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/qconfig.pri \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_functions.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_config.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/exclusive_builds.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_pre.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/debug.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_post.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/warn_on.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/unix/thread.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/moc.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/resources.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/uic.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/yacc.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/lex.prf \
		../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/include_source_dir.prf \
		/ifs/storage/ifs/otkach/Qt-4.5.2/lib/libQtGui.prl \
		/ifs/storage/ifs/otkach/Qt-4.5.2/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile percol2.pro
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/common/unix.conf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/qconfig.pri:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_functions.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt_config.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/exclusive_builds.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_pre.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/debug.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/default_post.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/warn_on.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/qt.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/unix/thread.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/moc.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/resources.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/uic.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/yacc.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/lex.prf:
../../../../storage/ifs/otkach/Qt-4.5.2/mkspecs/features/include_source_dir.prf:
/ifs/storage/ifs/otkach/Qt-4.5.2/lib/libQtGui.prl:
/ifs/storage/ifs/otkach/Qt-4.5.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile percol2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/percol21.0.0 || $(MKDIR) .tmp/percol21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/percol21.0.0/ && $(COPY_FILE) --parents mainwindow.h myparam.h percol2d.h plotter.h .tmp/percol21.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp myparam.cpp percol2d.cpp plotter.cpp .tmp/percol21.0.0/ && (cd `dirname .tmp/percol21.0.0` && $(TAR) percol21.0.0.tar percol21.0.0 && $(COMPRESS) percol21.0.0.tar) && $(MOVE) `dirname .tmp/percol21.0.0`/percol21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/percol21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) -r $(OBJECTS_DIR)/ti_files
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_myparam.cpp moc_plotter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_myparam.cpp moc_plotter.cpp
moc_mainwindow.cpp: percol2d.h \
		plotter.h \
		myparam.h \
		mainwindow.h
	/ifs/storage/ifs/otkach/Qt-4.5.2/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_myparam.cpp: myparam.h
	/ifs/storage/ifs/otkach/Qt-4.5.2/bin/moc $(DEFINES) $(INCPATH) myparam.h -o moc_myparam.cpp

moc_plotter.cpp: plotter.h
	/ifs/storage/ifs/otkach/Qt-4.5.2/bin/moc $(DEFINES) $(INCPATH) plotter.h -o moc_plotter.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp percol2d.h \
		mainwindow.h \
		plotter.h \
		myparam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		percol2d.h \
		plotter.h \
		myparam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

myparam.o: myparam.cpp myparam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myparam.o myparam.cpp

percol2d.o: percol2d.cpp percol2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o percol2d.o percol2d.cpp

plotter.o: plotter.cpp plotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotter.o plotter.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_myparam.o: moc_myparam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myparam.o moc_myparam.cpp

moc_plotter.o: moc_plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plotter.o moc_plotter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

