######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 15 02:05:35 2010
######################################################################

QT -= gui
TEMPLATE = app
TARGET = pdv
CONFIG += console
CONFIG -= app_bundle
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h percol2d.h
SOURCES += mpidistributions1.cpp mpimainwindow.cpp percol2d.cpp

include(pdv.pri)
